from importlib import metadata
from pathlib import Path


try:
    __version__ = metadata.version("pypddl")
except metadata.PackageNotFoundError:
    __version__ = "0.0.1"


def native_prefix() -> Path:
    return Path(__file__).resolve().parent / "native"

try:
    from ._pypddl import (
        Action,
        Atom,
        Axiom,
        BinaryArithmeticOperator,
        ActionBuilder,
        AtomBuilder,
        AxiomBuilder,
        BinaryFunctionExpressionBuilder,
        ConditionAndBuilder,
        ConditionBuilder,
        ConditionExistsBuilder,
        ConditionForallBuilder,
        ConditionImplyBuilder,
        ConditionLiteralBuilder,
        ConditionNotBuilder,
        ConditionNumericConstraintBuilder,
        ConditionOrBuilder,
        DomainBuilder,
        EffectAndBuilder,
        EffectBuilder,
        EffectForallBuilder,
        EffectLiteralBuilder,
        EffectNumericBuilder,
        EffectOneOfBuilder,
        EffectProbabilisticAlternativeBuilder,
        EffectProbabilisticBuilder,
        EffectWhenBuilder,
        FunctionExpressionBuilder,
        FunctionExpressionNumberBuilder,
        FunctionSkeletonBuilder,
        FunctionTermBuilder,
        InitialFunctionValueBuilder,
        LiteralBuilder,
        MetricBuilder,
        MultiFunctionExpressionBuilder,
        ObjectBuilder,
        ParameterBuilder,
        PredicateBuilder,
        RequirementBuilder,
        TaskBuilder,
        TermBuilder,
        TypeBuilder,
        UnaryFunctionExpressionBuilder,
        VariableBuilder,
        BinaryComparator,
        BinaryFunctionExpression,
        ConditionAnd,
        ConditionExists,
        ConditionForall,
        ConditionImply,
        ConditionLiteral,
        ConditionNot,
        ConditionNumericConstraint,
        ConditionOr,
        EffectAnd,
        EffectForall,
        EffectLiteral,
        EffectNumeric,
        EffectOneOf,
        EffectProbabilistic,
        EffectProbabilisticAlternative,
        EffectWhen,
        MultiFunctionExpression,
        UnaryFunctionExpression,
        FunctionExpression,
        FunctionExpressionNumber,
        ActionIndex,
        AtomIndex,
        AxiomIndex,
        BinaryFunctionExpressionIndex,
        ConditionAndIndex,
        ConditionExistsIndex,
        ConditionForallIndex,
        ConditionImplyIndex,
        ConditionIndex,
        ConditionLiteralIndex,
        ConditionNotIndex,
        ConditionNumericConstraintIndex,
        ConditionOrIndex,
        DomainIndex,
        EffectAndIndex,
        EffectForallIndex,
        EffectIndex,
        EffectLiteralIndex,
        EffectNumericIndex,
        EffectOneOfIndex,
        EffectProbabilisticAlternativeIndex,
        EffectProbabilisticIndex,
        EffectWhenIndex,
        FunctionExpressionIndex,
        FunctionExpressionNumberIndex,
        FunctionSkeletonIndex,
        FunctionTermIndex,
        InitialFunctionValueIndex,
        LiteralIndex,
        MetricIndex,
        MultiFunctionExpressionIndex,
        ObjectIndex,
        ParameterIndex,
        PredicateIndex,
        RequirementIndex,
        TaskIndex,
        TermIndex,
        TypeIndex,
        UnaryFunctionExpressionIndex,
        VariableIndex,
        FunctionSkeleton,
        FunctionTerm,
        InitialFunctionValue,
        Metric,
        MultiArithmeticOperator,
        NumericEffectOperator,
        UnaryArithmeticOperator,
        Condition,
        Domain,
        DomainTranslationResult,
        Effect,
        Literal,
        Object,
        Parameter,
        Parser,
        ParserOptions,
        Predicate,
        ProblemTranslationResult,
        Repository,
        RepositoryFactory,
        Requirement,
        RequirementKind,
        SemanticError,
        SemanticErrorCode,
        Task,
        Term,
        Type,
        Variable,
        translate_domain,
        translate_task,
    )
except ImportError:
    # Source-tree imports before building the extension still support native_prefix().
    pass
