from pathlib import Path

# Load public native dependency packages before this package loads native extensions.
import pyyggdrasil as pyyggdrasil

from . import formalism as formalism

__version__: str
__all__: tuple[str, ...]

def native_prefix() -> Path: ...
def native_include_dir() -> Path: ...
def native_lib_dir() -> Path: ...
def cmake_prefix() -> Path: ...
def cmake_dir() -> Path: ...
