from pathlib import Path

from . import formalism as formalism

__version__: str

def native_prefix() -> Path: ...
def native_include_dir() -> Path: ...
def native_lib_dir() -> Path: ...
def cmake_prefix() -> Path: ...
def cmake_dir() -> Path: ...
