function(loki_register_native_dependency_prefix native_prefix)
    if(NOT native_prefix)
        return()
    endif()

    set(native_include_dir_name "${CMAKE_INSTALL_INCLUDEDIR}")
    if(NOT native_include_dir_name)
        set(native_include_dir_name "include")
    endif()

    if(EXISTS "${native_prefix}/${native_include_dir_name}")
        list(APPEND LOKI_NATIVE_DEPENDENCY_INCLUDE_DIRECTORIES "${native_prefix}/${native_include_dir_name}")
        set(LOKI_NATIVE_DEPENDENCY_INCLUDE_DIRECTORIES "${LOKI_NATIVE_DEPENDENCY_INCLUDE_DIRECTORIES}" PARENT_SCOPE)
    endif()
endfunction()

function(loki_register_python_native_runtime_prefix package_relative_prefix)
    if(NOT package_relative_prefix)
        return()
    endif()

    set(native_lib_dir_name "${CMAKE_INSTALL_LIBDIR}")
    if(ARGC GREATER 1 AND ARGV1)
        foreach(candidate_lib_dir IN ITEMS "${ARGV1}/${CMAKE_INSTALL_LIBDIR}" "${ARGV1}/lib" "${ARGV1}/lib64")
            if(IS_DIRECTORY "${candidate_lib_dir}")
                get_filename_component(native_lib_dir_name "${candidate_lib_dir}" NAME)
                break()
            endif()
        endforeach()
    endif()

    list(APPEND LOKI_PYTHON_NATIVE_RUNTIME_PREFIXES "${package_relative_prefix}")
    list(APPEND LOKI_PYTHON_NATIVE_RUNTIME_LIBDIRS "${native_lib_dir_name}")
    set(LOKI_PYTHON_NATIVE_RUNTIME_PREFIXES "${LOKI_PYTHON_NATIVE_RUNTIME_PREFIXES}" PARENT_SCOPE)
    set(LOKI_PYTHON_NATIVE_RUNTIME_LIBDIRS "${LOKI_PYTHON_NATIVE_RUNTIME_LIBDIRS}" PARENT_SCOPE)
endfunction()

function(loki_make_python_native_runtime_rpaths output_variable origin package_relative_base)
    set(runtime_rpaths "${origin}")
    list(LENGTH LOKI_PYTHON_NATIVE_RUNTIME_PREFIXES runtime_prefix_count)
    if(runtime_prefix_count GREATER 0)
        math(EXPR runtime_prefix_last "${runtime_prefix_count} - 1")
        foreach(runtime_prefix_index RANGE ${runtime_prefix_last})
            list(GET LOKI_PYTHON_NATIVE_RUNTIME_PREFIXES ${runtime_prefix_index} package_relative_prefix)
            list(GET LOKI_PYTHON_NATIVE_RUNTIME_LIBDIRS ${runtime_prefix_index} native_lib_dir_name)
            list(APPEND runtime_rpaths "${origin}/${package_relative_base}${package_relative_prefix}/${native_lib_dir_name}")
        endforeach()
    endif()

    set("${output_variable}" "${runtime_rpaths}" PARENT_SCOPE)
endfunction()

function(loki_make_python_native_runtime_rpath_string output_variable origin package_relative_base)
    loki_make_python_native_runtime_rpaths(runtime_rpaths "${origin}" "${package_relative_base}")
    list(JOIN runtime_rpaths ":" runtime_rpath)
    set("${output_variable}" "${runtime_rpath}" PARENT_SCOPE)
endfunction()
