set(PYPDDL_STUB_ROOT "${CMAKE_INSTALL_PREFIX}/pypddl")

if(EXISTS "${PYPDDL_STUB_ROOT}")
    file(GLOB_RECURSE PYPDDL_STUB_FILES "${PYPDDL_STUB_ROOT}/*.pyi")

    foreach(PYPDDL_STUB_FILE IN LISTS PYPDDL_STUB_FILES)
        file(READ "${PYPDDL_STUB_FILE}" PYPDDL_STUB_CONTENT)
        set(PYPDDL_PATCHED_STUB_CONTENT "${PYPDDL_STUB_CONTENT}")

        string(REPLACE "pypddl._pypddl." "pypddl." PYPDDL_PATCHED_STUB_CONTENT "${PYPDDL_PATCHED_STUB_CONTENT}")
        string(REPLACE "pypddl._pypddl" "pypddl" PYPDDL_PATCHED_STUB_CONTENT "${PYPDDL_PATCHED_STUB_CONTENT}")

        if(NOT PYPDDL_STUB_CONTENT STREQUAL PYPDDL_PATCHED_STUB_CONTENT)
            file(WRITE "${PYPDDL_STUB_FILE}" "${PYPDDL_PATCHED_STUB_CONTENT}")
        endif()
    endforeach()
endif()
