function(loki_read_project_version out_var pyproject_file)
    if(NOT EXISTS "${pyproject_file}")
        message(FATAL_ERROR "pyproject.toml does not exist: ${pyproject_file}")
    endif()

    file(STRINGS "${pyproject_file}" pyproject_lines)
    set(in_project_table OFF)

    foreach(line IN LISTS pyproject_lines)
        string(STRIP "${line}" stripped_line)

        if(stripped_line MATCHES [=[^\[[^]]+\]$]=])
            string(LENGTH "${stripped_line}" table_line_length)
            math(EXPR table_name_length "${table_line_length} - 2")
            string(SUBSTRING "${stripped_line}" 1 "${table_name_length}" table_name)
            string(STRIP "${table_name}" table_name)
            if(table_name STREQUAL "project")
                set(in_project_table ON)
            else()
                set(in_project_table OFF)
            endif()
        elseif(in_project_table AND stripped_line MATCHES [=[^version[ 	]*=[ 	]*['"]([^'"]+)['"]]=])
            string(REGEX REPLACE [=[^version[ 	]*=[ 	]*['"]([^'"]+)['"].*$]=] "\\1" project_version "${stripped_line}")
            set(${out_var} "${project_version}" PARENT_SCOPE)
            return()
        endif()
    endforeach()

    message(FATAL_ERROR "Could not read [project].version from ${pyproject_file}")
endfunction()
