name: Apptainer
# Run for all pushes to the main branch and for all pull requests targeting the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    name: Build Apptainer image
    if: github.repository == 'planning-and-learning/loki'
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.4.3

      - name: Build image
        run: |
          apptainer build image.sif Apptainer

      - name: Login and deploy image
        if: (github.event_name != 'pull_request')
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login -u ${GITHUB_ACTOR} --password-stdin oras://ghcr.io
          REPO_LC="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
          apptainer push image.sif oras://ghcr.io/${REPO_LC}:latest
          # Image can now be pulled with "apptainer pull oras://ghcr.io/${REPO_LC}:latest"
