name: CI Ctest

on:
  push:
    branches-ignore:
      - test-pypi
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_type: Debug
          - os: macos-latest
            build_type: Release

    steps:
      - name: Checkout Loki
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install python requirements
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          python -m pip install --no-cache-dir 'pyyggdrasil==0.0.21'
        env:
          PIP_NO_CACHE_DIR: 1
          PYYGGDRASIL_JOBS: 2

      - name: Install CMake on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure and Build Loki
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DLOKI_BUILD_TESTS=ON \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DPython3_EXECUTABLE="$(python -c 'import sys; print(sys.executable)')" \
                -S . -B build_${{ matrix.build_type }} \
                -DCMAKE_PREFIX_PATH="$(python -c 'import pyyggdrasil; print(pyyggdrasil.native_prefix())')"
          cmake --build build_${{ matrix.build_type }} -j2

      - name: Run Tests
        working-directory: build_${{ matrix.build_type }}/tests/unit
        run: |
          NATIVE_LIB_DIR="$(python -c 'import pyyggdrasil; print(pyyggdrasil.native_prefix() / "lib")')"
          export DYLD_LIBRARY_PATH="${NATIVE_LIB_DIR}:$PWD/../../src:${DYLD_LIBRARY_PATH:-}"
          export LD_LIBRARY_PATH="${NATIVE_LIB_DIR}:$PWD/../../src:${LD_LIBRARY_PATH:-}"
          GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V
